### ISSUE TITLE
Unable to generate the change log

### ISSUE THREAD

**Issue by cfranc0** [justincy/github-action-npm-release#6]
Hello,

I've run into this issue today:

<img width="828" alt="image" src="https://github.com/justincy/github-action-npm-release/assets/20073894/bfd00b45-9964-4174-8baa-a5fe6cd32f7d">

The action code is simply
```yaml
- name: Automatic GitHub Release
  uses: justincy/github-action-npm-release@2.0.2
  id: release
```

But when I try to run the same command in my terminal, it seems to be working fine
```bash
$ git log 8017db07255d151fed69abce14cad59ce1276c41..HEAD --pretty=format:"- %h %s"

- d4ece6c Updated workflow version
- b1b789c Updated action code
...
```

**Comment by Johannes-Schiel** [comment]
i have the same bug, dont know what happend because i did not change anything :D

**Comment by fekitibi** [comment]
Did you find any workarounds? I am facing the same issue.

**Comment by fekitibi** [comment]
If you're encountering this issue, it's because the action is trying to generate changelogs using `git log`, but the commit history hasn't been fully fetched in the workflow.

To fix this, update your checkout action step to include the field `fetch-depth: 0`. This ensures that all branches and the complete commit history are fetched, allowing the action to generate the changelog successfully.

Here’s an example for clarity: 😄 
```yaml
- name: Checkout code
  uses: actions/checkout@v4
  with:
    fetch-depth: 0
```
